[build-system]
requires = [
  "setuptools>=64",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "KMC"
version = "0.0.1"
description = "Kinetic Monte Carlo"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
authors = [
  { name = "Leonardo Evaristo de Sousa", email = "ledso@dtu.dk" },
  { name = "Tiago de Sousa Araújo Cassiano" }
]

urls = { Homepage = "https://github.com/LeonardoESousa/xcharge" }

dependencies = [
  "numpy<2",
  "scipy",
  "joblib",
  "matplotlib",
  "tqdm",
  "pandas",
  "pymatgen",
]


[project.optional-dependencies]
dev = [
  "cython>=0.29.36",
  "pytest>=8",
]

[project.scripts]
kmc = "kmc.__main__:main"
build = "kmc.build_morph:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = [
  "tests",
  "tests.*",
  "*.tests",
  "*.tests.*",
  "pytest",
  "pytest.*",
]

[[tool.setuptools.ext-modules]]
name = "kmc.utils"
sources = ["kmc/utils.c"]
optional = true

[tool.pytest.ini_options]
testpaths = ["tests"]
