[build-system]
requires = [
  "setuptools>=64",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "KMC"
version = "0.0.1"
description = "Kinetic Monte Carlo"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.6"
license = {file= "LICENSE"}
authors = [
  { name = "Leonardo Evaristo de Sousa", email = "ledso@dtu.dk" },
  { name = "Tiago de Sousa Araújo Cassiano" }
]

urls = { Homepage = "https://github.com/LeonardoESousa/KMC" }

dependencies = [
  "numpy<2",
  "scipy",
  "joblib",
  "matplotlib",
  "tqdm",
  "importlib_metadata",
  "pandas",
  "pymatgen",
]


[project.optional-dependencies]
dev = [
  "cython>=0.29.36",
]

[project.scripts]
kmc = "kmc.__main__:main"
build = "kmc.build_morph:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = ["tests", "tests.*", "*.tests", "*.tests.*"]

[[tool.setuptools.ext-modules]]
name = "kmc.utils"
sources = ["kmc/utils.c"]
