name: Python package

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
- name: Install dependencies + package
  run: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade setuptools wheel
    python -m pip install pandas pytest
    python -m pip install .

- name: Test with pytest (equiv)
  run: pytest -s pytest/test_equiv.py

- name: Frenkel pair generation test
  run: pytest -s pytest/test_FP.py
